// Generated by packages/contracts/scripts/kernel-artifact.mjs.
// Kernel c960b42d2ed4adb0d5328f6e762962debdf8e57a; hashes are local build evidence, not public deployment receipts.
export const KERNEL_V4_ENTRY_POINT_V09 = "0x433709009b8330fda32311df1c2afa402ed8d009" as const;
export const KERNEL_V4_UUPS_IMPLEMENTATION_V09 =
  "0x6250926dd0309d9deaaeb4a2c413da5f3c4de37a" as const;
export const KERNEL_V4_FACTORY_V09 = "0x3d6d678742e276b6388fd06c1b8ecd19e2d64c2d" as const;
export const KERNEL_V4_FACTORY_V09_CODE_HASH =
  "0xc962dc5e7447a3188a1ec4827e668fee7adbcd426d1440dc8b1f8669697c9770" as const;
