import { describe, expect, it } from "vitest";
import * as protocol from "../src/index.js";

describe("package boundary", () => {
  it("exports only accepted grant, policy, identity, operation, permission, and capture owners", () => {
    expect(Object.keys(protocol).sort()).toEqual([
      "OAATH_GRANT_POLICY_HASH_DOMAIN",
      "OAATH_GRANT_POLICY_USAGE_VERSION",
      "OAATH_GRANT_POLICY_VERSION",
      "OAATH_GRANT_RECORD_VERSION",
      "OAATH_KERNEL_ACCOUNT_PROFILE_VERSION",
      "OAATH_OPERATION_RECORD_VERSION",
      "OAATH_OPERATOR_CREDENTIAL_PROFILE_VERSION",
      "OAATH_OWNER_CREDENTIAL_PROFILE_VERSION",
      "OAATH_PERMISSION_DECISION_HASH_DOMAIN",
      "OAATH_PERMISSION_DECISION_VERSION",
      "OAATH_PERMISSION_REQUEST_HASH_DOMAIN",
      "OAATH_PERMISSION_REQUEST_VERSION",
      "OaathGrantError",
      "OaathGrantPolicyError",
      "OaathIdentityProfileError",
      "OaathOperationError",
      "OaathPermissionProtocolError",
      "advanceGrant",
      "advanceOperation",
      "applyPermissionDecision",
      "applyVerifiedOperationObservation",
      "captureDenseArray",
      "captureRecord",
      "createGrant",
      "createGrantFromPermissionRequest",
      "createKernelAccountActionInput",
      "createOperation",
      "encodeGrantPolicy",
      "encodePermissionDecision",
      "encodePermissionRequest",
      "evaluateGrantPolicyCoverage",
      "exactCapturedRecord",
      "exactRecord",
      "hashGrantPolicy",
      "hashPermissionDecision",
      "hashPermissionRequest",
      "isGrantPolicyAttenuation",
      "operationOccupiesLane",
      "parseGrant",
      "parseGrantPolicy",
      "parseKernelAccountProfile",
      "parseOperation",
      "parseOperatorCredentialProfile",
      "parseOwnerCredentialProfile",
      "parsePermissionDecision",
      "parsePermissionRequest",
      "sameGrantIdentity",
    ]);
  });
});
