/**
 Cross-runtime and negative proofs for the reject-only Swift EIP-712 primitive.

 The accepted vectors live once under the protocol package and are verified
 there against viem. Swift parses that trusted fixture, then independently
 captures and hashes each canonical value with CryptoSwift Keccak-256.

 @author taek <leekt216@gmail.com>
 */
import Foundation
import XCTest
@testable import OwnerPhone

final class EIP712Tests: XCTestCase {
    func testSharedProtocolVectorsAndEveryMutationMatchExactly() throws {
        let fixture = try sharedFixture()
        XCTAssertEqual(fixture["version"] as? String, "oaath.eip712-hash-vectors/v1")
        let vectors = try XCTUnwrap(fixture["vectors"] as? [Any])
        XCTAssertEqual(vectors.count, 3)

        var mutationCount = 0
        for rawVector in vectors {
            let vector = try XCTUnwrap(rawVector as? [String: Any])
            let name = try XCTUnwrap(vector["name"] as? String)
            let typedData = try XCTUnwrap(vector["typedData"])
            let expected = try XCTUnwrap(vector["expectedDigest"] as? String)
            let digest = try deriveEIP712Digest(jsonValue: typedData)
            XCTAssertEqual(digest.canonicalHex, expected, name)
            XCTAssertEqual(
                try compareEIP712Digest(jsonValue: typedData, expectedDigest: expected),
                .matches(digest),
                name
            )

            for rawMutation in try XCTUnwrap(vector["mutations"] as? [Any]) {
                let mutation = try XCTUnwrap(rawMutation as? [String: Any])
                let mutated = try mutableJSONClone(typedData)
                try setJSONPointer(
                    try XCTUnwrap(mutation["pointer"] as? String),
                    in: mutated,
                    to: try XCTUnwrap(mutation["value"])
                )
                let mutationName = "\(name)/\(try XCTUnwrap(mutation["name"] as? String))"
                XCTAssertEqual(
                    try deriveEIP712Digest(jsonValue: mutated).canonicalHex,
                    try XCTUnwrap(mutation["expectedDigest"] as? String),
                    mutationName
                )
                mutationCount += 1
            }
        }
        XCTAssertEqual(mutationCount, 7)
    }

    func testOfficialMailVectorIsAnEthereumKeccakSanityCheck() throws {
        let fixture = try sharedFixture()
        let vectors = try XCTUnwrap(fixture["vectors"] as? [Any])
        let mail = try XCTUnwrap(vectors.first as? [String: Any])
        // SHA3-256 would not produce the official EIP-712 result. This exact
        // vector therefore guards CryptoSwift's Ethereum `.keccak256` variant.
        XCTAssertEqual(
            try deriveEIP712Digest(jsonValue: try XCTUnwrap(mail["typedData"])).canonicalHex,
            "0xbe609aee343fb3c4b28e1df9e632fca64fcfaede20f02e86244efddf30957bd2"
        )
    }

    func testEverySupportedFixedBytesAndIntegerWidthCapturesAndHashes() throws {
        for width in 1...32 {
            let value = "0x" + String(repeating: "ab", count: width)
            XCTAssertNoThrow(
                try deriveEIP712Digest(jsonValue: atomicTypedData(type: "bytes\(width)", value: value)),
                "bytes\(width)"
            )
        }
        for width in stride(from: 8, through: 256, by: 8) {
            XCTAssertNoThrow(
                try deriveEIP712Digest(jsonValue: atomicTypedData(type: "uint\(width)", value: "0")),
                "uint\(width)"
            )
            XCTAssertNoThrow(
                try deriveEIP712Digest(jsonValue: atomicTypedData(type: "int\(width)", value: "0")),
                "int\(width)"
            )
        }
    }

    func testCustomDependenciesAreAppendedInLexicographicOrder() throws {
        let typedData: [String: Any] = [
            "types": [
                "EIP712Domain": [["name": "chainId", "type": "uint256"]],
                "Zed": [["name": "value", "type": "uint8"]],
                "Alpha": [["name": "value", "type": "string"]],
                "Envelope": [
                    ["name": "z", "type": "Zed"],
                    ["name": "a", "type": "Alpha"]
                ]
            ],
            "primaryType": "Envelope",
            "domain": ["chainId": "1"],
            "message": [
                "z": ["value": "7"],
                "a": ["value": "sorted"]
            ]
        ]
        // Independently generated by viem from
        // Envelope(...)Alpha(...)Zed(...), regardless of dictionary order.
        XCTAssertEqual(
            try deriveEIP712Digest(jsonValue: typedData).canonicalHex,
            "0x6b92b63f2ad8789b3b3883019e4831a886e83e4529ebf3803530081d07efd7c4"
        )
    }

    func testNoncanonicalBuiltinLookalikesRemainValidCustomPrimaryTypes() throws {
        // The protocol parser treats these as custom struct identifiers when
        // they are primary types; only their use as field types is malformed.
        // Expected digests come from its viem-backed hash owner.
        let expected: [String: String] = [
            "bytes01": "0x4155c40d14764d9780e579fbd4554d6cfc2e049f03d99891ee476b795072d792",
            "uint08": "0x5c4c19850495bb71854dde11ba4a005e57002a9138606a091a425a55e2728397",
            "int08": "0x891231d7f70ec6ec639259195769c834b6bdbfad322b511de489785f0e537944"
        ]
        for (name, digest) in expected {
            let typedData: [String: Any] = [
                "types": [
                    "EIP712Domain": [["name": "chainId", "type": "uint256"]],
                    name: [["name": "value", "type": "uint8"]]
                ],
                "primaryType": name,
                "domain": ["chainId": "1"],
                "message": ["value": "7"]
            ]
            XCTAssertEqual(
                try deriveEIP712Digest(jsonValue: typedData).canonicalHex,
                digest,
                name
            )
        }
    }

    func testCompleteCanonicalDomainIncludingSaltHashesExactly() throws {
        let typedData: [String: Any] = [
            "types": [
                "EIP712Domain": [
                    ["name": "name", "type": "string"],
                    ["name": "version", "type": "string"],
                    ["name": "chainId", "type": "uint256"],
                    ["name": "verifyingContract", "type": "address"],
                    ["name": "salt", "type": "bytes32"]
                ],
                "Payload": [["name": "value", "type": "bool"]]
            ],
            "primaryType": "Payload",
            "domain": [
                "name": "All Domain",
                "version": "1",
                "chainId": "1",
                "verifyingContract": "0x1111111111111111111111111111111111111111",
                "salt": "0x" + String(repeating: "22", count: 32)
            ],
            "message": ["value": true]
        ]
        XCTAssertEqual(
            try deriveEIP712Digest(jsonValue: typedData).canonicalHex,
            "0x3ac52dd6ac256110c5203344548b781e439f6f41c8b3176824912eba6c1d649f"
        )
    }

    func testIntegerBoundsAndCanonicalDecimalStrings() throws {
        for value in ["-128", "127"] {
            XCTAssertNoThrow(try deriveEIP712Digest(
                jsonValue: atomicTypedData(type: "int8", value: value)
            ))
        }
        for value in ["0", "255"] {
            XCTAssertNoThrow(try deriveEIP712Digest(
                jsonValue: atomicTypedData(type: "uint8", value: value)
            ))
        }
        let minimumInt256 = "-57896044618658097711785492504343953926634992332820282019728792003956564819968"
        let maximumInt256 = "57896044618658097711785492504343953926634992332820282019728792003956564819967"
        XCTAssertNoThrow(try deriveEIP712Digest(
            jsonValue: atomicTypedData(type: "int256", value: minimumInt256)
        ))
        XCTAssertNoThrow(try deriveEIP712Digest(
            jsonValue: atomicTypedData(type: "int256", value: maximumInt256)
        ))

        for (type, value) in [
            ("int8", "-129"), ("int8", "128"),
            ("uint8", "-1"), ("uint8", "256"),
            ("int256", "-57896044618658097711785492504343953926634992332820282019728792003956564819969"),
            ("int256", "57896044618658097711785492504343953926634992332820282019728792003956564819968"),
            ("uint256", "115792089237316195423570985008687907853269984665640564039457584007913129639936"),
            ("uint256", "01"), ("int256", "-0")
        ] {
            assertEIP712Rejected(atomicTypedData(type: type, value: value), "\(type):\(value)")
        }
        // Foundation represents a JSON number as NSNumber. Integers must stay
        // canonical decimal strings at this boundary.
        assertEIP712Rejected(atomicTypedData(type: "uint256", value: NSNumber(value: 1)))
    }

    func testDynamicStringAndBytesBoundsAreUTF8AndDecodedByteBounds() throws {
        XCTAssertNoThrow(try deriveEIP712Digest(
            jsonValue: atomicTypedData(type: "string", value: String(repeating: "é", count: 8_192))
        ))
        assertEIP712Rejected(
            atomicTypedData(type: "string", value: String(repeating: "é", count: 8_193))
        )
        XCTAssertNoThrow(try deriveEIP712Digest(
            jsonValue: atomicTypedData(
                type: "bytes",
                value: "0x" + String(repeating: "ab", count: 16 * 1_024)
            )
        ))
        assertEIP712Rejected(atomicTypedData(
            type: "bytes",
            value: "0x" + String(repeating: "ab", count: 16 * 1_024 + 1)
        ))
        assertEIP712Rejected(atomicTypedData(type: "bytes", value: "0x0"))
        assertEIP712Rejected(atomicTypedData(type: "bytes2", value: "0xab"))
        assertEIP712Rejected(atomicTypedData(type: "bytes2", value: "0xABcd"))
    }

    func testNestedArraysDepthLengthAndFiniteRecursiveTypes() throws {
        XCTAssertNoThrow(try deriveEIP712Digest(jsonValue: recursiveEmptyNode()))

        let allowedType = "uint8" + String(repeating: "[]", count: 15)
        XCTAssertNoThrow(try deriveEIP712Digest(
            jsonValue: atomicTypedData(type: allowedType, value: nestedArray(depth: 15))
        ))
        let tooDeepType = "uint8" + String(repeating: "[]", count: 16)
        assertEIP712Rejected(
            atomicTypedData(type: tooDeepType, value: nestedArray(depth: 16))
        )
        assertEIP712Rejected(atomicTypedData(
            type: "uint8[]",
            value: Array(repeating: "0", count: 257)
        ))
        assertEIP712Rejected(atomicTypedData(
            type: "uint8[2]",
            value: ["0"]
        ))
    }

    func testMalformedTypesAndClosedObjectsFailBeforeEncoding() throws {
        for type in [
            "uint", "int", "uint08", "int08", "uint7", "uint264",
            "bytes01", "bytes0", "bytes33", "uint8[0]", "uint8[01]",
            "uint8[257]", "uint8[", "Missing"
        ] {
            assertEIP712Rejected(atomicTypedData(type: type, value: "0"), type)
        }

        let extra = try XCTUnwrap(try mutableJSONClone(atomicTypedData(type: "uint8", value: "1")) as? NSMutableDictionary)
        extra["extra"] = true
        assertEIP712Rejected(extra)

        let missing = try XCTUnwrap(try mutableJSONClone(atomicTypedData(type: "uint8", value: "1")) as? NSMutableDictionary)
        missing.removeObject(forKey: "message")
        assertEIP712Rejected(missing)

        let extraMessage = try XCTUnwrap(try mutableJSONClone(atomicTypedData(type: "uint8", value: "1")) as? NSMutableDictionary)
        let message = try XCTUnwrap(extraMessage["message"] as? NSMutableDictionary)
        message["extra"] = "no"
        assertEIP712Rejected(extraMessage)

        let uppercaseAddress = atomicTypedData(
            type: "address",
            value: "0x111111111111111111111111111111111111111A"
        )
        assertEIP712Rejected(uppercaseAddress)

        let unreferenced = try XCTUnwrap(try mutableJSONClone(atomicTypedData(type: "uint8", value: "1")) as? NSMutableDictionary)
        let types = try XCTUnwrap(unreferenced["types"] as? NSMutableDictionary)
        types["Unused"] = [["name": "value", "type": "bool"]]
        assertEIP712Rejected(unreferenced)

        let wrongDomainOrder: [String: Any] = [
            "types": [
                "EIP712Domain": [
                    ["name": "chainId", "type": "uint256"],
                    ["name": "name", "type": "string"]
                ],
                "Payload": [["name": "value", "type": "bool"]]
            ],
            "primaryType": "Payload",
            "domain": ["chainId": "1", "name": "wrong order"],
            "message": ["value": true]
        ]
        assertEIP712Rejected(wrongDomainOrder)
    }

    func testAliasedAndCyclicFoundationContainersFailClosed() throws {
        let aliased = try XCTUnwrap(try mutableJSONClone(pairTypedData()) as? NSMutableDictionary)
        let pair = try XCTUnwrap(aliased["message"] as? NSMutableDictionary)
        let shared = NSMutableDictionary(dictionary: ["value": "1"])
        pair["left"] = shared
        pair["right"] = shared
        assertEIP712Rejected(aliased)

        let cyclic = try XCTUnwrap(try mutableJSONClone(recursiveEmptyNode()) as? NSMutableDictionary)
        let node = NSMutableDictionary()
        let children = NSMutableArray()
        node["children"] = children
        children.add(node)
        cyclic["message"] = node
        assertEIP712Rejected(cyclic)
        children.removeAllObjects() // break the test-only retain cycle
    }

    func testIndependentEmptyJSONContainersAreNotMistakenForAliases() throws {
        let encoded = try JSONSerialization.data(withJSONObject: twoEmptyArraysTypedData())
        let decoded = try JSONSerialization.jsonObject(with: encoded)
        XCTAssertNoThrow(try captureCanonicalEIP712TypedData(jsonValue: decoded))

        let mutable = try XCTUnwrap(
            try mutableJSONClone(twoEmptyArraysTypedData()) as? NSMutableDictionary)
        let message = try XCTUnwrap(mutable["message"] as? NSMutableDictionary)
        let shared = NSMutableArray()
        message["left"] = shared
        message["right"] = shared
        assertEIP712Rejected(mutable)
    }

    func testCaptureDetachesFromMutableInputAndComparisonIsNonAuthorizingEvidence() throws {
        let fixture = try sharedFixture()
        let vectors = try XCTUnwrap(fixture["vectors"] as? [Any])
        let mail = try XCTUnwrap(vectors.first as? [String: Any])
        let input = try mutableJSONClone(try XCTUnwrap(mail["typedData"]))
        let captured = try captureCanonicalEIP712TypedData(jsonValue: input)
        let before = try deriveEIP712Digest(from: captured)
        try setJSONPointer("/message/contents", in: input, to: "mutated later")
        XCTAssertEqual(try deriveEIP712Digest(from: captured), before)

        let mismatch = try compareEIP712Digest(
            jsonValue: input,
            expectedDigest: before.canonicalHex
        )
        guard case let .mismatch(expected, derived) = mismatch else {
            return XCTFail("expected structured mismatch evidence")
        }
        XCTAssertEqual(expected, before.canonicalHex)
        XCTAssertNotEqual(derived, before)
        XCTAssertThrowsError(try compareEIP712Digest(
            jsonValue: input,
            expectedDigest: before.canonicalHex.uppercased()
        )) {
            XCTAssertEqual($0 as? EIP712DerivationError, .invalidExpectedDigest)
        }
    }
}

private func sharedFixture() throws -> [String: Any] {
    var repository = URL(fileURLWithPath: #filePath)
    for _ in 0..<5 { repository.deleteLastPathComponent() }
    let url = repository
        .appendingPathComponent("packages")
        .appendingPathComponent("protocol")
        .appendingPathComponent("test")
        .appendingPathComponent("fixtures")
        .appendingPathComponent("eip712-hash-vectors.json")
    let value = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
    return try XCTUnwrap(value as? [String: Any])
}

private func mutableJSONClone(_ value: Any) throws -> Any {
    let data = try JSONSerialization.data(withJSONObject: value)
    return try JSONSerialization.jsonObject(with: data, options: [.mutableContainers])
}

private func setJSONPointer(_ pointer: String, in root: Any, to value: Any) throws {
    let parts = pointer.split(separator: "/").map(String.init)
    guard pointer.hasPrefix("/"), !parts.isEmpty else {
        throw EIP712DerivationError.invalidField("test JSON pointer")
    }
    var cursor = root
    for part in parts.dropLast() {
        if let object = cursor as? NSDictionary, let next = object[part] {
            cursor = next
        } else if let array = cursor as? NSArray,
                  let index = Int(part), array.count > index {
            cursor = array.object(at: index)
        } else {
            throw EIP712DerivationError.invalidField("test JSON pointer")
        }
    }
    let final = try XCTUnwrap(parts.last)
    if let object = cursor as? NSMutableDictionary {
        object[final] = value
    } else if let array = cursor as? NSMutableArray,
              let index = Int(final), array.count > index {
        array[index] = value
    } else {
        throw EIP712DerivationError.invalidField("test JSON pointer")
    }
}

private func atomicTypedData(type: String, value: Any) -> [String: Any] {
    [
        "types": [
            "EIP712Domain": [["name": "chainId", "type": "uint256"]],
            "Payload": [["name": "value", "type": type]]
        ],
        "primaryType": "Payload",
        "domain": ["chainId": "1"],
        "message": ["value": value]
    ]
}

private func recursiveEmptyNode() -> [String: Any] {
    [
        "types": [
            "EIP712Domain": [["name": "chainId", "type": "uint256"]],
            "Node": [["name": "children", "type": "Node[]"]]
        ],
        "primaryType": "Node",
        "domain": ["chainId": "1"],
        "message": ["children": []]
    ]
}

private func pairTypedData() -> [String: Any] {
    [
        "types": [
            "EIP712Domain": [["name": "chainId", "type": "uint256"]],
            "Item": [["name": "value", "type": "uint8"]],
            "Pair": [
                ["name": "left", "type": "Item"],
                ["name": "right", "type": "Item"]
            ]
        ],
        "primaryType": "Pair",
        "domain": ["chainId": "1"],
        "message": ["left": ["value": "1"], "right": ["value": "2"]]
    ]
}

private func twoEmptyArraysTypedData() -> [String: Any] {
    [
        "types": [
            "EIP712Domain": [["name": "chainId", "type": "uint256"]],
            "Payload": [
                ["name": "left", "type": "string[]"],
                ["name": "right", "type": "string[]"]
            ]
        ],
        "primaryType": "Payload",
        "domain": ["chainId": "1"],
        "message": ["left": [Any](), "right": [Any]()]
    ]
}

private func nestedArray(depth: Int) -> Any {
    var value: Any = "1"
    for _ in 0..<depth { value = [value] }
    return value
}

private func assertEIP712Rejected(
    _ value: Any,
    _ message: String = "",
    file: StaticString = #filePath,
    line: UInt = #line
) {
    XCTAssertThrowsError(
        try captureCanonicalEIP712TypedData(jsonValue: value),
        message,
        file: file,
        line: line
    ) {
        XCTAssertNotNil($0 as? EIP712DerivationError, file: file, line: line)
    }
}
